### PR TITLE
Add ExternalMemorySortManager and MateVectorByRN

### PR DESCRIPTION
**Pull request by Griffan**

### CODE REVIEW

**Comment by pjvandehaar** [comment]
@mktrost The tests are all passing. They just look like they're failing because of changes to help.

If you like, I can move these changes over to bamUtil, remove whitespace changes, and replace all the hardcoded spaces with `printf("%*s" ...)`.

**Comment by mktrost** [comment]
That would be great, thanks.  I prefer not to let gotcloud/bamutil get
ahead of regular bamutil

**Comment by pjvandehaar** [comment]
Alright.  For the record, I meant `std::setw()`, not `printf()`.

**Comment by Griffan** [comment]
@pjvandehaar 
Hi, peter
I want to cancel this request first. Is there a way I can directly operate? Or Could you help me to reject this request.
Thanks!

**Comment by pjvandehaar** [comment]
@Griffan Are there things you'd like to change about your code?  Or can I go ahead and add your changes to bamUtil?

**Comment by Griffan** [comment]
@pjvandehaar 
yes, I updated a little bit. Maybe I should create another pull request

**Pull request closed without merging**
